<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Migration on Coding Blog By Arnab Shil</title><link>https://ruddra.com/tags/migration/</link><description>Recent content in Migration on Coding Blog By Arnab Shil</description><generator>Hugo -- gohugo.io</generator><language>en</language><lastBuildDate>Thu, 03 Jan 2019 02:00:00 +0000</lastBuildDate><atom:link href="https://ruddra.com/tags/migration/index.xml" rel="self" type="application/rss+xml"/><item><title>Django: Changing User Model in Mid-Project</title><link>https://ruddra.com/django-custom-user-migration-mid-phase-project/</link><pubDate>Thu, 03 Jan 2019 02:00:00 +0000</pubDate><guid>https://ruddra.com/django-custom-user-migration-mid-phase-project/</guid><description>Every now and then I see some questions pop up in Stack Overflow with title:
ValueError: Related model &amp;lsquo;app.User&amp;rsquo; cannot be resolved
This is a very common issue and pops up when the user tries to run the migration. So, lets talk more about what is this problem and how can we solve it.</description></item></channel></rss>