<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Models on Ruddra</title><link>https://ruddra.com/tags/models/</link><description>Recent content in Models on Ruddra</description><generator>Hugo -- gohugo.io</generator><lastBuildDate>Sat, 26 Jan 2019 14:58:58 +0600</lastBuildDate><atom:link href="https://ruddra.com/tags/models/index.xml" rel="self" type="application/rss+xml"/><item><title>Django: Ordering by Linked List for Model Objects</title><link>https://ruddra.com/posts/django-model-linked-list/</link><pubDate>Sat, 26 Jan 2019 14:58:58 +0600</pubDate><guid>https://ruddra.com/posts/django-model-linked-list/</guid><description>Linked list is a data structure where each object has points to next. In django, linked list can provide an interesting solution when it comes to custom ordering/grouping issues.
Lets think of an example like this= you are making a blog site, and you have made a Post Model like this:</description></item><item><title>Django: Changing User Model in Mid-Project</title><link>https://ruddra.com/posts/django-custom-user-migration-mid-phase-project/</link><pubDate>Thu, 03 Jan 2019 02:00:00 +0000</pubDate><guid>https://ruddra.com/posts/django-custom-user-migration-mid-phase-project/</guid><description>Every now and then I see some questions pop up in StackOverflow with title:
ValueError: Related model &amp;lsquo;app.User&amp;rsquo; cannot be resolved
This is a very common issue and pops up when the user tries to run the migration. So, lets talk more about what is this problem and how can we solve it.</description></item></channel></rss>